config/routes.rb
Rails.application.routes.draw do
  get 'favourites/potential_buyers/:house_id', to: 'favourites#potential_buyers'
  get 'favourites/add/:house_hunter_id/:house_id', to: 'favourites#add'
  get '/realtors/update_profile/:company_id', to: 'realtors#update_profile'
  get '/home', to: 'static_pages#home'
  resources :admins
  resources :names
  resources :searches
  resources :favourites
  resources :inquiries
  resources :houses
  resources :house_hunters
  resources :realtors
  resources :companies
  resources :replies
  root 'static_pages#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'searches/index'
  get 'search/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login" }, format: { with: EMAIL_FORMAT }
  validates :name, presence:true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :houses, dependent: :destroy
  has_many :realtors, dependent: :destroy

  #attr_accessor :name
  validates :name, :presence => true
  validates :website, :presence => true, uniqueness: true, format: { with: /\A((http|https):\/\/)?[a-zA-Z0-9\-#\/_]+[\.][a-zA-Z0-9\-\.#\/_]+\Z/i }
  validates :address, :presence => true
  validates :size, :presence => true, numericality: { only_integer: true }
  validates :year, :presence => true, numericality: { only_integer: true, greater_than: 1500, less_than_or_equal_to:  2018, message: "Invalid year" }, length: { maximum: 4,  too_long: "Invalid year" }
  validates :revenue, :presence => true, numericality: { only_integer: true }
  validates :synopsis, :presence => true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :house_hunter
  belongs_to :house

  validates :house_hunter_id, presence: true
  validates :house_id, presence: true
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :company
  belongs_to :realtor
  has_many :inquiries, dependent: :destroy
  has_many :favourites, dependent: :destroy

  validates :location, :presence => true
  validates :area, :presence => true    #Positive float validation
  validates :year, :presence => true, length: { maximum: 4,  too_long: "Invalid year" }, numericality: { only_integer: true, greater_than: 1500, less_than_or_equal_to:  2018, message: "Invalid year"}
  validates :style, :presence => true, format: { with: /single family|apartment|condo/i}
  validates :price, :presence => true, numericality: { only_integer: true }
  validates :floors, :presence => true, numericality: { only_integer: true }
  validates :basement, :presence => true, format: { with: /yes|no/i}
  validates :owner, :presence => true
  validates :realtor_id, :presence => true
  validates :company_id, :presence => true
  validates :name, :presence => true

  #adding the class of uploader to the model where it needs to be uploaded/shown
  mount_uploader :image, ImageUploader

end

app/models/house_hunter.rb
class HouseHunter < ApplicationRecord
  has_many :inquiries, dependent: :destroy
  has_many :favourites, dependent: :destroy

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login"  }, format: { with: EMAIL_FORMAT }
  validates :phone, presence: true, length: { maximum: 15 }
  validates :preferred, presence: true, format: { with: /email|text|phone/i, message: "Can only be email, text or phone"}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end


app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :house
  belongs_to :house_hunter
  has_many :replies, dependent: :destroy

  validates :subject, presence: true
  validates :message, presence: true
  validates :house_hunter_id, presence: true
  validates :house_id, presence: true
end

app/models/realtor.rb
class Realtor < ApplicationRecord
  has_many :houses
  has_many :replies, dependent: :destroy
  belongs_to :company

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login" }, format: { with: EMAIL_FORMAT }
  validates :name, presence: true
  validates :password, presence: true, confirmation: true
  validates :phone, presence: true, length: { maximum: 15 }
  validates :company_id, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :realtor
  belongs_to :inquiry

  validates :realtor_id, presence: true
  validates :inquiry_id, presence: true
  validates :message, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
  def search_houses
    houses = House.all
    houses = houses.where("lower(location) like ?", "%#{location.downcase}%") if location.present?
    # house = house.where(category_id: category_id) if category_id.present?
    houses = houses.where("price >= ?", min_price) if min_price.present?
    houses = houses.where("price <= ?", max_price) if max_price.present?
    houses = houses.where("area >= ?", min_area) if min_area.present?
    houses = houses.where("area <= ?", max_area) if max_area.present?
    houses
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user, role)
  session[:user_id] = user.id
   session[:role] = role
  end

  def current_user
    if session[:user_id]
      if session[:role]=='Realtor'
        @current_user ||= Realtor.includes(:company).find_by(id: session[:user_id])
      else if session[:role]=='House Hunter'
             @current_user ||= HouseHunter.find_by(id: session[:user_id])
           else
             @current_user ||= Admin.find_by(id: session[:user_id])
      end
    end
    end
    end

  def logged_in?
  !current_user.nil?
 # cookies[:role]
  end

  def log_out
    session.delete :user_id
    session.delete :role
    @current_user = nil
  end

end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :admin_name, class: 'form-control' %>
  </div>

  <div class="field form-control">
    <%= form.label :email %>
    <%= form.text_field :email, id: :admin_email, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :password %>
    <%= form.text_field :password, id: :admin_password, class: 'form-control' %>
    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation, id: :admin_password, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<% if logged_in? %>
  <% if session[:role] == 'House Hunter'%>
    <script type="text/javascript">
        window.location.href="/house_hunters/<%= current_user.id %>"
    </script>
  <% else %>
    <% if session[:role] == 'Realtor'%>
      <script type="text/javascript">
          window.location.href="/realtors/<%= current_user.id %>"
      </script>
    <% else %>
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>
<a href="javascript:history.back()">Back</a>

      <% end %>
  <% end %>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  // put your correct path in a string here
  </script>
<% end %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<a href="javascript:history.back()">Back</a>

app/views/admins/show.html.erb
<% if logged_in?  && session[:role] == 'Admin'%>
  <p id="notice"><%= notice %></p>
  <div class="center jumbotron">
    <h1 >Admin Panel</h1>
  </div>
  <div class="container">
    <div class="col-md-4 col-md-offset-5">

      <p>
        <strong>Name:</strong>
        <%= @admin.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @admin.email %>
      </p>
      <%#= link_to 'Edit', edit_admin_path(@admin) %>
      <br>
      <%= link_to 'Edit Admin Details', edit_admin_path(@admin) , class: "btn btn-default" %>

    </div>
  </div>
  <br>
  <br>
  <br>

  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="row center form">
        <h1>Manage Companies</h1>
        <%= link_to 'List Companies',  companies_path, class: 'btn btn-success', style: 'color:#FFFFFF;'%><br><br>
        <%= link_to 'Create Company', new_company_path, class: 'btn btn-primary', style: 'color:#FFFFFF;'%>
      </div>
    </div>
  </div>

  <br><br>

  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="row center form">
        <h1>Manage Houses</h1>
        <%= link_to 'View Houses', houses_path, class: 'btn btn-success', style: 'color:#FFFFFF;'%><br><br>
        <%= link_to 'New House', new_house_path, class: 'btn btn-primary', style: 'color:#FFFFFF;'%>
      </div>
    </div>
  </div>

  <br><br>

  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="row center form">
        <h1>Manage Realtors</h1>
        <%= link_to 'List Realtors', realtors_path, class: 'btn btn-success', style: 'color:#FFFFFF;'%><br><br>
        <%= link_to 'New Realtor', new_realtor_path, class: 'btn btn-primary', style: 'color:#FFFFFF;'%>
        <br><br><%= link_to 'Realtor\'s account', @realtor, class: 'btn btn-danger', style: 'color:#FFFFFF;'%>
      </div>
    </div>
  </div>

  <br><br>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="row center form">
        <h1>Manage House Hunters</h1>
        <%= link_to 'List House Hunters', house_hunters_path, class: 'btn btn-success', style: 'color:#FFFFFF;'%><br><br>
        <%= link_to 'Create House Hunter', new_house_hunter_path , class: 'btn btn-primary', style: 'color:#FFFFFF;'%>
        <br><br><%= link_to 'House Hunter\'s account', @house_hunter, class: 'btn btn-danger', style: 'color:#FFFFFF;'%>
      </div>
    </div>
  </div>
  <br><br>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  // put your correct path in a string here
  </script>
<% end %>