config/routes.rb
Rails.application.routes.draw do
  get 'favourites/potential_buyers/:house_id', to: 'favourites#potential_buyers'
  get 'favourites/add/:house_hunter_id/:house_id', to: 'favourites#add'
  get '/realtors/update_profile/:company_id', to: 'realtors#update_profile'
  get '/home', to: 'static_pages#home'
  resources :admins
  resources :names
  resources :searches
  resources :favourites
  resources :inquiries
  resources :houses
  resources :house_hunters
  resources :realtors
  resources :companies
  resources :replies
  root 'static_pages#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'searches/index'
  get 'search/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    #@houses = House.all
    @houses = House.where(nil) # creates an anonymous scope
    @houses = @houses.location(params[:location]) if params[:location].present?
    @houses = @houses.price(params[:price]) if params[:price].present?
    @houses = @houses.area(params[:area]) if params[:area].present?
  end

  def change

  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
    if logged_in? && session[:role] == 'Realtor'
    @company = Company.find_by(id: current_user.company_id)
      end
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    val = house_params
    if session[:role] == 'Realtor'
    val[:company_id] = current_user.company_id
    end
    @house = House.includes(:company, :realtor).new(val)
    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:location, :area, :year, :style, :price, :floors, :basement, :owner, :buyers, :company_id, :realtor_id, :name, :image)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
</head>
<body>
  <%= form_with(model: house, local: true, :html => {:multipart => true}) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="col-md-4 col-md-offset-3">
      <div class="row form">

        <%# -------------NAME------------ %>
        <div class="field form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :house_name, class: 'form-control', placeholder: "Enter Name"   %>
        </div>

  <%# -------------COMPANY------------ %>
  <% if session[:role] == 'Admin' %>
  <%= form.label "Company" %>
  <%= select("house", "company_id", Company.all.collect{ |c| [ c.name, c.id ] if c.id !=1 }, {class: "form-control"}) %>
<% else %>
    <%= form.label "Company" %>
      <%= form.select :company_id, [[current_user.company.name, current_user.company_id]], {class: "form-control"} %>
    <% end %>

        <%# -------------LOCATION------------ %>
        <div class="field form-group">
          <%= form.label :location %>
          <%= form.text_field :location, id: :house_location, class: 'form-control', placeholder: "Enter location"   %>
        </div>

        <%# -------------SQUARE FOOTAGE----------- %>
        <div class="field form-group">
          <%= form.label :area %>
          <%= form.text_field :area, id: :house_area, class: 'form-control', placeholder: "Enter area"   %>
        </div>

        <%# -------------YEAR------------ %>
        <div class="field form-group">
          <%= form.label :year %>
          <%= form.text_field :year, id: :house_year, class: 'form-control', placeholder: "Enter year"   %>
        </div>

        <%# -------------STYLE------------ %>
        <div class="field form-group">
          <%= form.label :style %>
          <%= form.select :style, ['Apartment', 'Single Family', 'Condo'], { include_blank: true }, id: :house_style, class: "form-control"%>
        </div>

        <%# -------------PRICE------------ %>
        <div class="field">
          <%= form.label :price %>
          <%= form.text_field :price, id: :house_price, class: 'form-control', placeholder: "Enter price"   %>
        </div>

        <%# -------------FLOORS------------ %>
        <div class="field">
          <%= form.label :floors %>
          <%= form.number_field :floors, id: :house_floors, min: 0 , class: 'form-control', placeholder: "Enter floor size"  %>
        </div>

        <%# -------------BASEMENT------------ %>
        <div class="field form-group">
          <%= form.label :basement %>
          <%= form.select :basement, ['Yes', 'No'], { include_blank: true }, id: :house_basement, class: "form-control"%>
        </div>

        <%# --------------OWNER -------------- %>
        <div class="field">
          <%= form.label :owner %>
          <%= form.text_field :owner, id: :house_owner , class: 'form-control', placeholder: "Enter Owner"  %>
        </div>

  <%# -------------REALTOR CONTACT------------ %>
   <% if session[:role] == 'Admin' %>
  <div class="field">
    <%= form.label "Realtor" %>
    <%= select("house", "realtor_id", Realtor.all.collect{ |c| [ c.name, c.id ]}, { include_blank: true }, {class: "form-control"}) %>
        <% else %>
          <%= form.label "Realtor" %>
          <%= form.select :realtor_id, [[current_user.name, current_user.id]], {class: "form-control"} %>
        <% end %>
  </div>

        <%# -------------Image upload----------------- %>
        <div class="field form-group">
          <%= form.label "Upload House Image"%>
          <%= form.file_field :image , class: 'btn btn-default'%>
        </div>
        <br>
        <div class="actions form-group">
          <%= form.submit 'Create House', class: 'btn btn-primary'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

</body>
</html>

app/views/houses/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
</head>
<body>
	<% if logged_in? %>
  <% if session[:role] == 'House Hunter'%>
    <script type="text/javascript">
        window.location.href="/house_hunters/<%= current_user.id %>"
    </script>
  <% else %>
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<a href="javascript:history.back()">Back</a>
  <% end %>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>

</body>
</html>

app/views/houses/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
    .house{
  background-color:gold; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin-left: 470px;

    }
  </style>
</head>
<body>
  <% if logged_in? %>
<p id="notice"><%= notice %></p>
  <h1>Houses</h1>
  <div class="jumbotron">
    <table class="table">
      <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Location</th>
      <th scope="col">Company</th>
      <th scope="col">Area</th>
      <th scope="col">Year</th>
      <th scope="col">Style</th>
      <th scope="col">Price</th>
      <th scope="col">Floors</th>
      <th scope="col">Basement</th>
      <th scope="col">Owner</th>
      <th scope="col">Realtor's Contact</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% if session[:role] == 'Realtor' && current_user.company_id == 1  %>
      <p> You can't view any houses. Register to or create a company first</p>
    <% else %>
    <% @houses.each do |house| %>
    <% if session[:role] == 'Realtor' && current_user.company_id == house.company_id || session[:role] == 'House Hunter' || session[:role] == 'Admin' %>
        <tr>
        <td scope="row"><%= house.name %></td>
        <td scope="row"><%= house.location %></td>
        <td scope="row"><%= house.company.name %></td>
        <td scope="row"><%= house.area %></td>
        <td scope="row"><%= house.year %></td>
        <td scope="row"><%= house.style %></td>
        <td scope="row"><%= house.price %></td>
        <td scope="row"><%= house.floors %></td>
        <td scope="row"><%= house.basement %></td>
        <td scope="row"><%= house.owner %></td>
        <td scope="row"><%= house.realtor.phone %></td>
        <td><%= link_to 'Show', house %></td>
        <td>
          <% unless session[:role] == 'House Hunter'%>  <%# Only Logged in Realtor and Admin has access %>
            <td> <%= link_to 'Potential Buyers', "/favourites/potential_buyers/#{house.id}"  %></td>
            <% if session[:role] == 'Admin' || house.realtor_id == current_user.id %>
              <td>
            <%= link_to 'Edit', edit_house_url(house) %>
             <%= link_to 'Delete', house, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
              <% end %>
          <%end %>
          <% if session[:role] == 'House Hunter' || session[:role] == 'Admin' %>
            <td><%= link_to 'Favourite', "/favourites/add/#{current_user.id}/#{house.id}"%></td>
            <% end %>
        </td>
      </tr>
    <% end %>
      <% end %>
    </tbody>
  </table>
  </div>
  <br>
    <% unless session[:role] == 'Realtor' %>
    <div class="house"><%= link_to "Search Houses", new_search_path %>
      <% end %> |
  <% if session[:role] == 'Realtor' || session[:role] == 'Admin' %>
    <%= link_to "New House", { :controller => "houses", :action => "new" } %>
    <% end %>
  <a href="javascript:history.back()">Back</a>
    <% end %>
  <% else %>
  <script type="text/javascript">
      window.location.href="/login"  // put your correct path in a string here
  </script>
<% end %>
</div>

</body>
</html>

app/views/houses/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
</head>
<body>
<% if logged_in? %>
  <% if session[:role] == 'Realtor' && current_user.company_id == 1  %>
    <p> You can't view any houses. Register to or create a company first</p>
  <% else %>
  <% if session[:role] == 'House Hunter'%>
    <script type="text/javascript">
        window.location.href="/house_hunters/<%= current_user.id %>"
    </script>
  <% else %>
    <h1>New House</h1>

    <%= render 'form', house: @house %>
    <br>
    <div class="container">
      <div class="col-md-4 col-md-offset-5">
        <a href="javascript:history.back()" class="btn btn-default">Back</a>
      </div>
    </div>
  <% end %>
    <% end %>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>
</body>
</html>

app/views/houses/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
   <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>

</head>
<body>
  <table id="customers">

<% if logged_in? %>
<p id="notice"><%= notice %></p>

  <thead>
    <tr>
    <th style="width: 100px;"><strong>Name</strong></th>
    <th style="width: 100px;"><strong>Location</strong></th>
    <th style="width: 100px;"><strong>Company</strong></th>
    <th style="width: 100px;"><strong>Area</strong></th>
    <th style="width: 100px;"><strong>Year</strong></th>
    <th style="width: 100px;"><strong>Style</strong></th>
    <th style="width: 100px;"><strong>Price</strong></th>
    <th style="width: 100px;"><strong>Floors</strong></th>
    <th style="width: 100px;"><strong>Basement</strong></th>
    <th style="width: 100px;"><strong>Owner</strong></th>
    <th style="width: 100px;"><strong>Realtor's contact</strong></th>
    <th style="width: 100px;"><strong>Image of the House</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @house.name %></td>
      <td><%= @house.location %></td>
      <td><%= @house.company.name %></td>
      <td><%= @house.area %></td>
      <td><%= @house.year %></td>
      <td><%= @house.style %></td>
      <td><%= @house.price %></td>
      <td><%= @house.floors %></td>
      <td><%= @house.basement %></td>
      <td><%= @house.owner %></td>
      <td><%= @house.realtor.phone %></td>
      <td><%= image_tag @house.image_url.to_s %></td>
    </tr>
  </tbody>
</table>

  <% unless session[:role] == 'House Hunter'%>
    <%= link_to 'Potential Buyers', "/favourites/potential_buyers/#{@house.id}"  %>
    <% end %>
</p>
<% if session[:role] == 'Admin' || session[:role] == 'Realtor' && current_user.company_id == @house.company_id%>
<%= link_to 'Edit', edit_house_path(@house) %>
    <% end %>
  <a href="javascript:history.back()" class="btn btn-primary">Back</a>
  <% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>
</body>
</html>