config/routes.rb
Rails.application.routes.draw do
  get 'favourites/potential_buyers/:house_id', to: 'favourites#potential_buyers'
  get 'favourites/add/:house_hunter_id/:house_id', to: 'favourites#add'
  get '/realtors/update_profile/:company_id', to: 'realtors#update_profile'
  get '/home', to: 'static_pages#home'
  resources :admins
  resources :names
  resources :searches
  resources :favourites
  resources :inquiries
  resources :houses
  resources :house_hunters
  resources :realtors
  resources :companies
  resources :replies
  root 'static_pages#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'searches/index'
  get 'search/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/realtor.rb
class Realtor < ApplicationRecord
  has_many :houses
  has_many :replies, dependent: :destroy
  belongs_to :company

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login" }, format: { with: EMAIL_FORMAT }
  validates :name, presence: true
  validates :password, presence: true, confirmation: true
  validates :phone, presence: true, length: { maximum: 15 }
  validates :company_id, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/realtors_controller.rb
class RealtorsController < ApplicationController
  before_action :set_realtor, only: [:show, :edit, :update, :destroy]

  # GET /realtors
  # GET /realtors.json
  def index
    @realtors = Realtor.all
  end

  # GET /realtors/1
  # GET /realtors/1.json
  def show
    if logged_in?
    @realtor = Realtor.find_by(email: current_user.email)
      end
  end

  # GET /realtors/new
  def new
    @realtor = Realtor.new
  end

  # GET /realtors/1/edit
  def edit
  end

  # POST /realtors
  # POST /realtors.json
  def create
    val = realtor_params
    if val[:company_id].blank?
      val[:company_id] = 1
      @realtor = Realtor.includes(:company).new(val)
    else
    @realtor = Realtor.includes(:company).new(realtor_params)
    end
    respond_to do |format|
      if @realtor.save
        unless logged_in?
        log_in @realtor, "Realtor"
          flash[:notice] = "Welcome #{@realtor.name}"
        end
        format.html { redirect_to current_user  }
        format.json { render :show, status: :created, location: @realtor }
       else
        format.html { render :new }
        format.json { render json: @realtor.errors, status: :unprocessable_entity }
      end
    end
    end

  # PATCH/PUT /realtors/1
  # PATCH/PUT /realtors/1.json
  def update
    val = realtor_params
    if val[:company_id].blank?
      val[:company_id] = 1
     end
    respond_to do |format|
      if @realtor.update(val)
        flash[:notice] = 'Your profile was updated!'
        format.html { redirect_to @realtor }
        format.json { render :show, status: :ok, location: @realtor }
      else
        format.html { render :edit }
        format.json { render json: @realtor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_profile
    @realtor = Realtor.find_by(id: current_user.id)
        @realtor.update_attribute(:company_id, params[:company_id])
    redirect_to @realtor
  end

  # DELETE /realtors/1
  # DELETE /realtors/1.json
  def destroy
    @realtor.destroy
    respond_to do |format|
      format.html { redirect_to realtors_url, notice: 'Realtor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_realtor
      @realtor = Realtor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def realtor_params
      params.require(:realtor).permit(:email, :name, :password, :phone, :company_id, :password_confirmation)
    end
end

app/helpers/realtors_helper.rb
module RealtorsHelper
end

app/views/realtors/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
</head>
<body>
<%= form_with(model: realtor, local: true) do |form| %>
  <% if realtor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(realtor.errors.count, "error") %> prohibited this realtor from being saved:</h2>

      <ul>
      <% realtor.errors.full_messages.each do |message| %>
<li><%= message %></li>
    <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="col-md-4 col-md-offset-3">
      <div class="row form">

        <%# ----------------NAME---------------%>
        <div class="field form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :realtor_name, class: 'form-control', placeholder: "Enter Name"%>
        </div>

        <%# ----------------EMAIL---------------%>
        <div class="field form-group">
          <%= form.label :email %>
          <%= form.text_field :email, id: :realtor_email, class: 'form-control', placeholder: "Enter email" %>
        </div>


        <%# ----------------PASSWORD---------------%>
        <div class="field form-group">
          <%= form.label :password %>
          <%= form.password_field :password, id: :realtor_password, class: 'form-control', placeholder: "Enter Password" %>
          <br>
          <%= form.label :password_confirmation, "Confirm password" %>
          <%= form.password_field :password_confirmation, id: :realtor_password, class: 'form-control', placeholder: "Enter Password again"  %>
        </div>

        <%# ----------------PHONE---------------%>
        <div class="field form-group">
          <%= form.label :phone %>
          <%= form.text_field :phone, id: :realtor_phone, class: 'form-control', placeholder: "Enter Phone Number"  %>
        </div>

        <%# ----------------COMPANY---------------%>
        <div class="form-group">
          <%= form.label :company_id %>
          <%= select("realtor", "company_id", Company.all.collect{ |c| [ c.name, c.id ] if c.id !=1}, {class: "form-control"})%>
        </div>

        <div class="actions form-group">
          <%= form.submit 'Submit', class: 'btn btn-primary'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

</body>
</html> 

app/views/realtors/edit.html.erb
 <!DOCTYPE html>
 <html>
 <head>
 	<title></title>
 	<style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
 </head>
 <body>
 <% if logged_in? %>
  <% if session[:role] == 'House Hunter'%>
    <script type="text/javascript">
        window.location.href="/house_hunters/<%= current_user.id %>"
    </script>
  <% else %>
<h1>Editing Realtor</h1>

<%= render 'form', realtor: @realtor %>
<div class="btn btn-primary" style="margin-left: 520px;">
<%= link_to 'Show', @realtor %> |
    <a href="javascript:history.back()">Back</a>
</div>
<% end %>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>
 </body>
 </html>

app/views/realtors/index.html.erb
 <!DOCTYPE html>
 <html>
 <head>
   <title></title>
   <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
 </head>
 <body>
 <% if logged_in?%>
  <%if session[:role] == 'Admin' %>

<!-- <p id="notice"><%= notice %></p>
 -->
<h1>Realtors</h1>
    <div class="jumbotron">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope ="col">Name</th>
      <th scope ="col">Email</th>
      <th scope ="col">Phone</th>
      <th scope ="col">Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @realtors.each do |realtor| %>
      <tr>
        <td scope ="row"><%= realtor.name %></td>
        <td scope ="row"><%= realtor.email %></td>
        <td scope ="row"><%= realtor.phone %></td>
        <% if realtor.company_id == 1 %>
        <td scope ="row"><%= " " %></td>
          <% else %>
        <td scope ="row"><%= realtor.company.name %></td>
          <% end %>
        <td><%= link_to 'Show', realtor %></td>
        <td><%= link_to 'Edit', edit_realtor_path(realtor) %></td>
        <td><%= link_to 'Destroy', realtor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
<br>
<%= link_to 'New Realtor', new_realtor_path %>
    <a href="javascript:history.back()">Back</a>
<% else %>
<% if session[:role] == 'Realtor' %>
  <script type="text/javascript">
      window.location.href="/realtors/<%= current_user.id %>"
  </script>
<% else %>
  <script type="text/javascript">
      window.location.href="/house_hunters/<%= current_user.id %>"
  </script>
<% end %>
<% end %>
<% else %>
<script type="text/javascript">
    window.location.href="/login"  //Redirect to login for unlogged in users
</script>
<% end %>

 </body>
 </html>

app/views/realtors/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Realtor</title>
  <style type="text/css">
    .body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: -40px;
  width: auto;
  height: auto;
  background-image: url(https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*);
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0;
}
.heading{
  position: absolute;
  margin-top: 15px;
  margin-left: -30px;
  text-align: center;
  background-color: black;
  color: white;
  padding-left: 20px;
  padding-right: 20px;
}
    
  </style>
</head>
<body>
<div class="body"></div>
<% if logged_in? && session[:role] =='Admin' || !logged_in? %>
  <h1 class="heading">New Realtor</h1>

  <%= render 'form', realtor: @realtor %>
  <br>
  <div class="container">
    <div class="col-md-4 col-md-offset-5">
      <a href="javascript:history.back()" class="btn btn-default">Back</a>
    </div>
  </div>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>
</body>
</html>

app/views/realtors/show.html.erb
 <!DOCTYPE html>
 <html>
 <head>
   <title></title>
   <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
  </style>
 </head>
 <body>
  <table id="customers">
 <% if logged_in?%>
  <% if session[:role] == 'House Hunter' %>
    <script type="text/javascript">
        window.location.href="/house_hunters/<%= current_user.id %>"
    </script>
  <% else %>
<!-- <p id="notice"><%= notice %></p>
 -->
 <h1>Profile</h1>
 <thead>
   <tr>
     <th><strong>Name</strong></th>
     <th><strong>Email</strong></th>
     <th><strong>Phone</strong></th>
     <th><strong>Company</strong></th>
     <th></th>
     <th></th>
     <th></th>
     <th></th>
   </tr>
 </thead>
 <tbody>
   <tr>
     <td><%= @realtor.name %></td>
     <td><%= @realtor.email %></td>
     <td><%= @realtor.phone %></td>
      <% if @realtor.company_id != 1 %>
      <td><%= @realtor.company.name %></td>
      <td><%= link_to 'Edit Profile', edit_realtor_path(@current_user) %></td>
      <td><%= link_to 'View Houses', houses_path %></td>
      <td><%= link_to 'Post House', new_house_path %></td>
      <td><%= link_to 'View Inquiries', inquiries_path %></td>
  
      <% else %>
    <%= link_to 'Choose existing company', edit_realtor_path(@current_user) %>  |  <%= link_to 'Add your company', new_company_path %>
    <% end %>
   </tr>
 </tbody>

  <% if @realtor.company_id != 1 %>
      <font size="6" color="white"><%= @realtor.company.name %></font>
    <% else %>
   <%= link_to 'Choose existing company', edit_realtor_path(@current_user) %>  |  <%= link_to 'Add your company', new_company_path %>
    <% end %>
</p>

  <% end %>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>
</table>
 </body>
 </html>