config/routes.rb
Rails.application.routes.draw do
  get 'favourites/potential_buyers/:house_id', to: 'favourites#potential_buyers'
  get 'favourites/add/:house_hunter_id/:house_id', to: 'favourites#add'
  get '/realtors/update_profile/:company_id', to: 'realtors#update_profile'
  get '/home', to: 'static_pages#home'
  resources :admins
  resources :names
  resources :searches
  resources :favourites
  resources :inquiries
  resources :houses
  resources :house_hunters
  resources :realtors
  resources :companies
  resources :replies
  root 'static_pages#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'searches/index'
  get 'search/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/house_hunter.rb
class HouseHunter < ApplicationRecord
  has_many :inquiries, dependent: :destroy
  has_many :favourites, dependent: :destroy

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login"  }, format: { with: EMAIL_FORMAT }
  validates :phone, presence: true, length: { maximum: 15 }
  validates :preferred, presence: true, format: { with: /email|text|phone/i, message: "Can only be email, text or phone"}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end


app/controllers/house_hunters_controller.rb
class HouseHuntersController < ApplicationController
  before_action :set_house_hunter, only: [:show, :edit, :update, :destroy]

  # GET /house_hunters
  # GET /house_hunters.json
  def index
    @house_hunters = HouseHunter.all
  end

  # GET /house_hunters/1
  # GET /house_hunters/1.json
  def show
    if logged_in?
    @house_hunter = HouseHunter.find_by(id: current_user.id)
      end
  end

  # GET /house_hunters/new
  def new
    @house_hunter = HouseHunter.new
  end

  # GET /house_hunters/1/edit
  def edit
  end

  # POST /house_hunters
  # POST /house_hunters.json
  def create
    @house_hunter = HouseHunter.new(house_hunter_params)

    respond_to do |format|
      if @house_hunter.save
        unless logged_in?
          log_in @house_hunter, "House Hunter"
          flash[:notice] = "Welcome #{@house_hunter.name}"
        end
        format.html { redirect_to current_user  }
        format.json { render :show, status: :created, location: @house_hunter }
      else
        format.html { render :new }
        format.json { render json: @house_hunter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /house_hunters/1
  # PATCH/PUT /house_hunters/1.json
  def update
    respond_to do |format|
      if @house_hunter.update(house_hunter_params)
        format.html { redirect_to @house_hunter, notice: 'House hunter was successfully updated.' }
        format.json { render :show, status: :ok, location: @house_hunter }
      else
        format.html { render :edit }
        format.json { render json: @house_hunter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /house_hunters/1
  # DELETE /house_hunters/1.json
  def destroy
    @house_hunter.destroy
    respond_to do |format|
      format.html { redirect_to house_hunters_url, notice: 'House hunter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house_hunter
      @house_hunter = HouseHunter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_hunter_params
      params.require(:house_hunter).permit(:email, :password, :name, :phone, :preferred)
    end
end

app/helpers/house_hunters_helper.rb
module HouseHuntersHelper
end

app/views/house_hunters/_form.html.erb
<%= form_with(model: house_hunter, local: true) do |form| %>
  <% if house_hunter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house_hunter.errors.count, "error") %> prohibited this house_hunter from being saved:</h2>

      <ul>
        <% house_hunter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="col-md-4 col-md-offset-3">
      <div class="row form">

        <%# ----------------HOUSE HUNTER NAME---------------%>
        <div class="field form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :house_hunter_name,class: 'form-control',  placeholder: "Enter Name"  %>
        </div>

        <%# ----------------EMAIL---------------%>
        <div class="field form-group">
          <%= form.label :email %>
          <%= form.email_field :email, id: :house_hunter_email, class: 'form-control', placeholder: "Enter Email"  %>
        </div>

        <%# ----------------PASSWORD---------------%>
        <div class="field form-group">
          <%= form.label :password %>
          <%= form.password_field :password, id: :realtor_password, class: 'form-control', placeholder: "Enter Password" %><br>
          <%= form.label :password_confirmation, "Confirm Password" %>
          <%= form.password_field :password_confirmation, id: :house_hunter_password, class: 'form-control', placeholder: "Enter password again"  %>
        </div>

        <%# ----------------PHONE---------------%>
        <div class="field form-group">
          <%= form.label "Contact Number" %>
          <%= form.text_field :phone, id: :house_hunter_phone,class: 'form-control', placeholder: "Enter Phone"  %>
        </div>

        <%# ----------------PREFERRED---------------%>
        <div class="field form-group">
          <%= form.label "Preferred contact" %>
          <%= form.select :preferred, ['Email', 'Text', 'Phone'], { include_blank: true }, id: :house_hunter_preferred, class: "form-control" %>
        </div>

        <div class="actions form-group">
          <%= form.submit  'Submit', class: 'btn btn-primary'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/house_hunters/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: 0px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0
    }
    .Show{
      margin-left: 500px;
      background-color:gold; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;

    }
  </style>
</head>
<body>
  <% if logged_in? %>
  <% if session[:role] == 'Realtor'%>
    <script type="text/javascript">
        window.location.href="/realtors/<%= current_user.id %>"
    </script>
  <% else %>
<h1>Editing House Hunter</h1>

<%= render 'form', house_hunter: @house_hunter %>
<div class="Show"><%= link_to 'Show', @house_hunter %> |
    <a href="javascript:history.back()">Back</a>
  <% end %>
</div>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>

</body>
</html>

app/views/house_hunters/index.html.erb
<% if logged_in?%>
  <%if session[:role] == 'Admin' %>
<p id="notice"><%= notice %></p>

<h1>House Hunters</h1>
    <div class="jumbotron">
      <table class="table">
        <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @house_hunters.each do |house_hunter| %>
      <tr>
        <td scope="row"><%= house_hunter.name %></td>
        <td scope="row"><%= house_hunter.email %></td>
        <td scope="row"><%= house_hunter.phone %></td>
        <td><%= link_to 'Show', house_hunter %></td>
        <td><%= link_to 'Edit', edit_house_hunter_path(house_hunter) %></td>
        <td><%= link_to 'Destroy', house_hunter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
<br>
<%= link_to 'New House Hunter', new_house_hunter_path %>
    <a href="javascript:history.back()">Back</a>
 <% else %>
    <% if session[:role] == 'Realtor' %>
    <script type="text/javascript">
        window.location.href="/realtors/<%= current_user.id %>"
    </script>
      <% else %>
      <script type="text/javascript">
          window.location.href="/house_hunters/<%= current_user.id %>"
      </script>
    <% end %>
    <% end %>
<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>

app/views/house_hunters/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sign up</title>
  <style type="text/css">
    
.body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: -40px;
  width: auto;
  height: auto;
  background-image: url("https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/brewster-mcleod-architects-1486154143.jpg?crop=1.00xw:1.00xh;0,0&resize=980:*");
  background-size: cover;
  /*-webkit-filter: blur(5px);*/
  z-index: 0;
}
.heading{
  position: absolute;
  margin-top: 15px;
  margin-left: -30px;
  text-align: center;
  background-color: black;
  color: white;
  padding-left: 20px;
  padding-right: 20px;
}


  </style>
</head>
<body>

<div class="body"></div>
  <% if logged_in? && session[:role] =='Admin' || !logged_in? %>
  <h1 class="heading">New House Hunter</h1>

  <%= render 'form', house_hunter: @house_hunter %>

  <br>
  <div class="container">
    <div class="col-md-4 col-md-offset-5">
      <a href="javascript:history.back()" class="btn btn-default">Back</a>
    </div>
  </div>


<% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>

</body>
</html>

app/views/house_hunters/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>dashboard page</title>
  <style type="text/css">
    body{
  position: absolute;
  top:  -20px;
  left: -20px;
  right: -40px;
  bottom: -40px;
  width: auto;
  height: auto;
  background-image: url("https://image.shutterstock.com/image-photo/small-house-garden-blurred-background-260nw-273977312.jpg");
  background-size: cover;
/*  -webkit-filter: blur(5px);
*/  z-index: 0;

    }
   
  </style>
</head>
<body>

 <% if logged_in?%>
  <% if session[:role] == 'Realtor' %>
    <script type="text/javascript">
    window.location.href="/realtors/<%= current_user.id %>"
    </script>
    <% end %>

 <h1 style="color: black; margin-right: 100px;" ><strong>Welcome <%= @house_hunter.name.capitalize + "!!!" %></strong>
</h1>
<legend>
  <table class="table">
    <thead class="thead-dark">
      
      <tr>
        <th scope="col" style="width: 100px" >
        <font size="5"><strong>Name</strong></font>
        </th>
        <th scope="col" style="width: 100px">
        <font size="5"><strong>Email</strong></font>
        </th>
        <th scope="col" style="width: 100px">
        <font size="5"><strong>Phone Number</strong></font>
        </th>
        
        <tbody>
          <td style="width: 100px;color: white;size: 6"><%= @house_hunter.name %></td>
          <td style="width: 100px;color: white;"><%= @house_hunter.email %></td>
          <td style="width: 100px;color: white;"><%= @house_hunter.phone %></td>
        </tbody>
       
       </tr>
      </table>
    </thead>
  <table class="table">
  <thead class="thead-dark">
  <td style="width: 100px;"><%= link_to 'Edit', edit_house_hunter_path(@house_hunter), class: "link" %></td> <br><br>

 <td style="width: 100px;"><%= link_to 'View Inquiries', inquiries_path, class: "link"  %></td><br><br>

   <td style="width: 100px;"><%= link_to 'View Houses', houses_path , class: "link" %></td><br><br>

  <td style="width: 100px;"><%= link_to 'View Companies', companies_path, class: "link"  %></td><br><br>

 <td style="width: 100px;"><%= link_to 'View Favourites', favourites_path, class: "link"  %></td><br><br>
  <% else %>
  <script type="text/javascript">
      window.location.href="/login"  //Redirect to login for unlogged in users
  </script>
<% end %>
</thead>
</table>
</table>
</legend>

</body>
</html>
   